# Stage 1: Build environment
FROM node:22-alpine

# Set the working directory for the application
WORKDIR /usr/src/app

# Accept build argument for npm_token
ARG NPM_TOKEN

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Update and upgrade packages, then install necessary dependencies
RUN apk update && \
    apk upgrade

# Stage 2: Node environment

# Install necessary packages including ca-certificates, bash, and PostgreSQL client
RUN apk --no-cache add bash postgresql-client

# Create .npmrc file with authentication
RUN if [ -n "$NPM_TOKEN" ]; then \
    echo "NPM_TOKEN is set"; \
    echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > .npmrc; \
    echo "@joinworth:registry=https://npm.pkg.github.com" >> .npmrc; \
    echo "always-auth=true" >> .npmrc; \
else \
    echo "Warning: No NPM_TOKEN provided, private packages may fail to install"; \
fi
# Install Node.js dependencies without executing scripts
RUN npm ci --ignore-scripts --no-audit --no-fund

# Copy necessary files and directories for database migrations and seeding
COPY ./db ./db/
COPY .db-migraterc .db-migraterc
COPY ./db/migrations/scripts/migration_entrypoint.sh ./

COPY ./tsconfig.json ./tsconfig.json
COPY ./src/configs ./src/configs/
COPY ./src/utils ./src/utils/

# Run DB migrations and seed attributes
CMD [ "sh", "-c", "npm run migrate:up && npm run seed:attributes" ]
