from integrationsdata import IntegrationsData
import numpy
import math
class PrepareData:
    def _get_financial_value(self, key):
        value = self.scoreInput.get(key)
        try:
            return self._safe_float(value) / 1000 if value is not None else numpy.nan
        except Exception:
            return numpy.nan
    def get_score_input(self, inputForScore):
        try:
            return inputForScore.get("score_input", {})
        except Exception:
            return {}
    # def __init__(self):
    #     try:
    #         # integrtionsDataObj = IntegrationsData()
    #         # self.integrtionsDataObj = integrtionsDataObj
    #     except Exception:
    #         raise
        
    def _safe_float(self, value):
        try:
            return float(value)
        except (TypeError, ValueError):
            return numpy.nan

    def mappedData(self, inputForScore):
        try:
            integrationsDataObj = IntegrationsData(inputForScore)
            self.integrtionsDataObj = integrationsDataObj
            self.economicsData = integrationsDataObj.get_economics_data()
            self.scoreInput = self.get_score_input(inputForScore)


            # data = {
            #     'gdp_pch': self.economicsData.get("gdp_pch", numpy.nan),
            #     'gdp_pc1': self.economicsData.get("gdp_pc1", numpy.nan),
            #     't10y2y': self.economicsData.get("t10y2y", numpy.nan),
            #     't10y2y_chg': self.economicsData.get("t10y2y_chg", numpy.nan),
            #     't10y2y_ch1': self.economicsData.get("t10y2y_ch1", numpy.nan),
            #     't10y': self.economicsData.get("t10y", numpy.nan),
            #     't10y_chg': self.economicsData.get("t10y_chg", numpy.nan),
            #     't10y_ch1': self.economicsData.get("t10y_ch1", numpy.nan),
            #     't2y': self.economicsData.get("t2y", numpy.nan),
            #     't2y_chg': self.economicsData.get("t2y_chg", numpy.nan),
            #     't2y_ch1': self.economicsData.get("t2y_ch1", numpy.nan),
            #     'brent_pch': self.economicsData.get("brent_pch", numpy.nan),
            #     'brent_pc1': self.economicsData.get("brent_pc1", numpy.nan),
            #     'wtispot_pch': self.economicsData.get("wtispot_pch", numpy.nan),
            #     'wtispot_pc1': self.economicsData.get("wtispot_pc1", numpy.nan),
            #     'vix': self.economicsData.get("vix", numpy.nan),
            #     'vix_chg': self.economicsData.get("vix_chg", numpy.nan),
            #     'vix_ch1': self.economicsData.get("vix_ch1", numpy.nan),
            #     'csentiment': self.economicsData.get("csentiment", numpy.nan),
            #     'csentiment_chg': self.economicsData.get("csentiment_chg", numpy.nan),
            #     'csentiment_ch1': self.economicsData.get("csentiment_ch1", numpy.nan),
            #     'dolindx': self.economicsData.get("dolindx", numpy.nan),
            #     'dolindx_chg': self.economicsData.get("dolindx_chg", numpy.nan),
            #     'dolindx_ch1': self.economicsData.get("dolindx_ch1", numpy.nan),
            #     'unemp': self.economicsData.get("unemp", numpy.nan),
            #     'unemp_chg': self.economicsData.get("unemp_chg", numpy.nan),
            #     'unemp_ch1': self.economicsData.get("unemp_ch1", numpy.nan),
            #     'cpi': self.economicsData.get("cpi", numpy.nan),
            #     'cpi_chg': self.economicsData.get("cpi_chg", numpy.nan),
            #     'cpi_ch1': self.economicsData.get("cpi_ch1", numpy.nan),
            #     'cpicore': self.economicsData.get("cpicore", numpy.nan),
            #     'cpicore_chg': self.economicsData.get("cpicore_chg", numpy.nan),
            #     'cpicore_ch1': self.economicsData.get("cpicore_ch1", numpy.nan),
            #     'ccdelinq': self.economicsData.get("ccdelinq", numpy.nan),
            #     'ccdelinq_chg': self.economicsData.get("ccdelinq_chg", numpy.nan),
            #     'ccdelinq_ch1': self.economicsData.get("ccdelinq_ch1", numpy.nan),
            #     'cloandelinq': self.economicsData.get("cloandelinq", numpy.nan),
            #     'cloandelinq_chg': self.economicsData.get("cloandelinq_chg", numpy.nan),
            #     'cloandelinq_ch1': self.economicsData.get("cloandelinq_ch1", numpy.nan),
            #     'busloandelinq': self.economicsData.get("busloandelinq", numpy.nan),
            #     'busloandelinq_chg': self.economicsData.get("busloandelinq_chg", numpy.nan),
            #     'busloandelinq_ch1': self.economicsData.get("busloandelinq_ch1", numpy.nan),
            #     'wagegrowth': self.economicsData.get("wagegrowth", numpy.nan),
            #     'wagegrowth_chg': self.economicsData.get("wagegrowth_chg", numpy.nan),
            #     'usdeur': self.economicsData.get("usdeur", numpy.nan),
            #     'usdeur_chg': self.economicsData.get("usdeur_chg", numpy.nan),
            #     'usdeur_ch1': self.economicsData.get("usdeur_ch1", numpy.nan),
            #     'usdpeso': self.economicsData.get("usdpeso", numpy.nan),
            #     'usdpeso_chg': self.economicsData.get("usdpeso_chg", numpy.nan),
            #     'usdpeso_ch1': self.economicsData.get("usdpeso_ch1", numpy.nan),
            #     'usdcan': self.economicsData.get("usdcan", numpy.nan),
            #     'usdcan_chg': self.economicsData.get("usdcan_chg", numpy.nan),
            #     'usdcan_ch1': self.economicsData.get("usdcan_ch1", numpy.nan),
            #     'ppi_chg': self.economicsData.get("ppi_chg", numpy.nan),
            #     'ppi_ch1': self.economicsData.get("ppi_ch1", numpy.nan),
            #     'location_cnt': self.equifaxData.get("location_cnt", numpy.nan),
            #     'location_active_cnt': self.equifaxData.get("location_active_cnt", numpy.nan),
            #     'location_inactive_cnt': self.equifaxData.get("location_inactive_cnt", numpy.nan),
            #     'location_inactiveold_cnt': self.equifaxData.get("location_inactiveold_cnt", numpy.nan),
            #     'location_inactivedt_cnt': self.equifaxData.get("location_inactivedt_cnt", numpy.nan),
            #     'location_latitude_avg': self.equifaxData.get("location_latitude_avg", numpy.nan),
            #     'location_longitude_avg': self.equifaxData.get("location_longitude_avg", numpy.nan),
            #     'location_soho_cnt': self.equifaxData.get("location_soho_cnt", numpy.nan),
            #     'location_biz_cnt': self.equifaxData.get("location_biz_cnt", numpy.nan),
            #     'location_res_cnt': self.equifaxData.get("location_res_cnt", numpy.nan),
            #     'location_small_cnt': self.equifaxData.get("location_small_cnt", numpy.nan),
            #     'location_large_cnt': self.equifaxData.get("location_large_cnt", numpy.nan),
            #     'location_unknown_size_cnt': self.equifaxData.get("location_unknown_size_cnt", numpy.nan),
            #     'location_gov_cnt': self.equifaxData.get("location_gov_cnt", numpy.nan),
            #     'location_fedgov_cnt': self.equifaxData.get("location_fedgov_cnt", numpy.nan),
            #     'location_nonprofitind_cnt': self.equifaxData.get("location_nonprofitind_cnt", numpy.nan),
            #     'location_edu_cnt': self.equifaxData.get("location_edu_cnt", numpy.nan),
            #     'location_indsole_cnt': self.equifaxData.get("location_indsole_cnt", numpy.nan),
            #     'location_partner_cnt': self.equifaxData.get("location_partner_cnt", numpy.nan),
            #     'location_limpartner_cnt': self.equifaxData.get("location_limpartner_cnt", numpy.nan),
            #     'location_corp_cnt': self.equifaxData.get("location_corp_cnt", numpy.nan),
            #     'location_scorp_cnt': self.equifaxData.get("location_scorp_cnt", numpy.nan),
            #     'location_llc_cnt': self.equifaxData.get("location_llc_cnt", numpy.nan),
            #     'location_llp_cnt': self.equifaxData.get("location_llp_cnt", numpy.nan),
            #     'location_other_cnt': self.equifaxData.get("location_other_cnt", numpy.nan),
            #     'location_ccorp_cnt': self.equifaxData.get("location_ccorp_cnt", numpy.nan),
            #     'location_nonprofitstat_cnt': self.equifaxData.get("location_nonprofitstat_cnt", numpy.nan),
            #     'location_mutual_cnt': self.equifaxData.get("location_mutual_cnt", numpy.nan),
            #     'location_trust_cnt': self.equifaxData.get("location_trust_cnt", numpy.nan),
            #     'location_lllp_cnt': self.equifaxData.get("location_lllp_cnt", numpy.nan),
            #     'bankrupt_cnt_failrt': self.equifaxData.get("bankrupt_cnt_failrt", numpy.nan),
            #     'bankrupt_cnt_credcls': self.equifaxData.get("bankrupt_cnt_credcls", numpy.nan),
            #     'bankrupt_cnt_field': self.equifaxData.get("bankrupt_cnt_field", numpy.nan),
            #     'corpemployees': self.equifaxData.get("corpemployees", numpy.nan),
            #     'corpamount': self.equifaxData.get("corpamount", self.integrtionsDataObj.get_is_revenue_yearly()), ## if not found in equifax, map to revenue,
            #     'creditscore_avg': self.equifaxData.get("creditscore_avg", numpy.nan),
            #     'creditscore_max': self.equifaxData.get("creditscore_max", numpy.nan),
            #     'creditscore_min': self.equifaxData.get("creditscore_min", numpy.nan),
            #     'creditperc_avg': self.equifaxData.get("creditperc_avg", numpy.nan),
            #     'creditperc_max': self.equifaxData.get("creditperc_max", numpy.nan),
            #     'creditperc_min': self.equifaxData.get("creditperc_min", numpy.nan),
            #     'mkt_telscore_avg': self.equifaxData.get("mkt_telscore_avg", numpy.nan),
            #     'mkt_telscore_max': self.equifaxData.get("mkt_telscore_max", numpy.nan),
            #     'mkt_telscore_min': self.equifaxData.get("mkt_telscore_min", numpy.nan),
            #     'mkt_totalscore_avg': self.equifaxData.get("mkt_totalscore_avg", numpy.nan),
            #     'mkt_totalscore_max': self.equifaxData.get("mkt_totalscore_max", numpy.nan),
            #     'mkt_totalscore_min': self.equifaxData.get("mkt_totalscore_min", numpy.nan),
            #     'months_since_update': self.equifaxData.get("months_since_update", numpy.nan),
            #     'legname_occ': self.equifaxData.get("legname_occ", numpy.nan),
            #     'afflname_occ': self.equifaxData.get("afflname_occ", numpy.nan),
            #     'ratio_accounts_payable_cash': numpy.nan,
            #     'ratio_total_liabilities_cash': self.integrtionsDataObj.get_ratio_total_liabilities_cash(),
            #     'ratio_total_liabilities_assets': self.integrtionsDataObj.get_ratio_total_liabilities_assets(),
            #     'ratio_return_on_equity': self.integrtionsDataObj.get_ratio_returnonequityroe(),
            #     'ratio_return_on_assets': self.integrtionsDataObj.get_ratio_returnonassetsroa(),
            #     'ratio_net_income_ratio': self.integrtionsDataObj.get_is_net_income_ratio(),
            #     'ratio_income_quality_ratio': self.integrtionsDataObj.get_ratio_incomequalityratio(),
            #     'ratio_gross_margin': self.integrtionsDataObj.get_ratio_grossmargin(),
            #     'ratio_equity_multiplier': self.integrtionsDataObj.get_ratio_equitymultiplier(),
            #     'ratio_debt_to_equity': self.integrtionsDataObj.get_ratio_debttoequityratio(),
            #     'ratio_operating_margin': self.integrtionsDataObj.get_ratio_operatingmargin(),
            #     'ratio_cash_ratio': self.integrtionsDataObj.get_ratio_cash_ratio(),
            #     'ratio_accounts_recievable_cash': numpy.nan,
            #     'flag_total_liabilities_over_assets': self.integrtionsDataObj.get_custom_total_liabilities_over_assets_ratio(),
            #     'flag_equity_negative': 0 if self.integrtionsDataObj.get_bs_total_equity() >= 0 else 1,
            #     'flag_net_income_negative': 0 if self.integrtionsDataObj.get_is_net_income() >= 0 else 1,
            #     'is_revenue': self.integrtionsDataObj.get_is_revenue(),
            #     'is_operating_expense': self.integrtionsDataObj.get_is_operating_expense(),
            #     'is_net_income': self.integrtionsDataObj.get_is_net_income(),
            #     'is_gross_profit': self.integrtionsDataObj.get_is_gross_profit(),
            #     'is_cost_of_goods_sold': self.integrtionsDataObj.get_is_cost_of_goods_sold(),
            #     'cf_operating_cash_flow': self.integrtionsDataObj.get_cf_operating_cash_flow(),
            #     'cf_cash_at_end_of_period': self.integrtionsDataObj.get_cf_cash_end_of_period(),
            #     'cf_capex': numpy.nan,
            #     'bs_total_liabilities_and_equity': self.integrtionsDataObj.get_bs_total_liabilities() + self.integrtionsDataObj.get_bs_total_equity(),
            #     'bs_total_liabilities': self.integrtionsDataObj.get_bs_total_liabilities(),
            #     'bs_total_equity': self.integrtionsDataObj.get_bs_total_equity(),
            #     'bs_total_debt': self.integrtionsDataObj.get_bs_total_liabilities(),
            #     'bs_total_assets': self.integrtionsDataObj.get_bs_total_assets(),
            #     'bs_accounts_receivable': numpy.nan, #TODO,
            #     'bs_accounts_payable': numpy.nan, #TODO,
            #     'review_score': self.integrtionsDataObj.get_review_score(),
            #     'review_cnt': self.integrtionsDataObj.get_review_count(),
            #     'min_age': self.integrtionsDataObj.get_min_age(),
            #     'max_age': self.integrtionsDataObj.get_min_age(),
            #     'lien_count': self.equifaxData.get("lien_count", numpy.nan),
            #     'lien_most_recent_age': self.equifaxData.get("lien_most_recent_age", numpy.nan),
            #     'bankruptcy_count': self.equifaxData.get("bankruptcy_count", numpy.nan),
            #     'bankruptcy_most_recent_age': self.equifaxData.get("bankruptcy_most_recent_age", numpy.nan),
            #     'judgement_count': self.equifaxData.get("judgement_count", numpy.nan),
            #     'judgement_most_recent_age': self.equifaxData.get("judgement_most_recent_age", numpy.nan),
            #     'primnaics_sector': self.equifaxData.get("primnaics_sector", numpy.nan),
            #     'primnaics_subsector': self.equifaxData.get("primnaics_subsector", numpy.nan),
            #     'primnaics_industry': self.equifaxData.get("primnaics_industry", numpy.nan),
            #     'legultstateall': self.equifaxData.get("legultstateall", numpy.nan),
            #     'primnaicscode': self.equifaxData.get("primnaicscode", numpy.nan),
            #     'corpamount_prec': self.equifaxData.get("corpamount_prec", numpy.nan),
            #     'corpamount_type': self.equifaxData.get("corpamount_type", numpy.nan),
            #     'primnaics_industry_group': self.equifaxData.get("primnaics_industry_group", numpy.nan),
            #     'failrate_avg': self.equifaxData.get("failrate_avg", numpy.nan),
            #     'primsic': self.equifaxData.get("primsic", numpy.nan),
            #     'missing_fields_share': 0
            # }
            
            # data = {
            #     'gdp_pch': self.economicsData.get("gdp_pch", numpy.nan),
            #     'gdp_pc1': self.economicsData.get("gdp_pc1", numpy.nan),
            #     't10y2y': self.economicsData.get("t10y2y", numpy.nan),
            #     't10y2y_chg': self.economicsData.get("t10y2y_chg", numpy.nan),
            #     't10y2y_ch1': self.economicsData.get("t10y2y_ch1", numpy.nan),
            #     't10y': self.economicsData.get("t10y", numpy.nan),
            #     't10y_chg': self.economicsData.get("t10y_chg", numpy.nan),
            #     't10y_ch1': self.economicsData.get("t10y_ch1", numpy.nan),
            #     't2y': self.economicsData.get("t2y", numpy.nan),
            #     't2y_chg': self.economicsData.get("t2y_chg", numpy.nan),
            #     't2y_ch1': self.economicsData.get("t2y_ch1", numpy.nan),
            #     'brent_pch': self.economicsData.get("brent_pch", numpy.nan),
            #     'brent_pc1': self.economicsData.get("brent_pc1", numpy.nan),
            #     'wtispot_pch': self.economicsData.get("wtispot_pch", numpy.nan),
            #     'wtispot_pc1': self.economicsData.get("wtispot_pc1", numpy.nan),
            #     'vix': self.economicsData.get("vix", numpy.nan),
            #     'vix_chg': self.economicsData.get("vix_chg", numpy.nan),
            #     'vix_ch1': self.economicsData.get("vix_ch1", numpy.nan),
            #     'csentiment': self.economicsData.get("csentiment", numpy.nan),
            #     'csentiment_chg': self.economicsData.get("csentiment_chg", numpy.nan),
            #     'csentiment_ch1': self.economicsData.get("csentiment_ch1", numpy.nan),
            #     'dolindx': self.economicsData.get("dolindx", numpy.nan),
            #     'dolindx_chg': self.economicsData.get("dolindx_chg", numpy.nan),
            #     'dolindx_ch1': self.economicsData.get("dolindx_ch1", numpy.nan),
            #     'unemp': self.economicsData.get("unemp", numpy.nan),
            #     'unemp_chg': self.economicsData.get("unemp_chg", numpy.nan),
            #     'unemp_ch1': self.economicsData.get("unemp_ch1", numpy.nan),
            #     'cpi': self.economicsData.get("cpi", numpy.nan),
            #     'cpi_chg': self.economicsData.get("cpi_chg", numpy.nan),
            #     'cpi_ch1': self.economicsData.get("cpi_ch1", numpy.nan),
            #     'cpicore': self.economicsData.get("cpicore", numpy.nan),
            #     'cpicore_chg': self.economicsData.get("cpicore_chg", numpy.nan),
            #     'cpicore_ch1': self.economicsData.get("cpicore_ch1", numpy.nan),
            #     'ccdelinq': self.economicsData.get("ccdelinq", numpy.nan),
            #     'ccdelinq_chg': self.economicsData.get("ccdelinq_chg", numpy.nan),
            #     'ccdelinq_ch1': self.economicsData.get("ccdelinq_ch1", numpy.nan),
            #     'cloandelinq': self.economicsData.get("cloandelinq", numpy.nan),
            #     'cloandelinq_chg': self.economicsData.get("cloandelinq_chg", numpy.nan),
            #     'cloandelinq_ch1': self.economicsData.get("cloandelinq_ch1", numpy.nan),
            #     'busloandelinq': self.economicsData.get("busloandelinq", numpy.nan),
            #     'busloandelinq_chg': self.economicsData.get("busloandelinq_chg", numpy.nan),
            #     'busloandelinq_ch1': self.economicsData.get("busloandelinq_ch1", numpy.nan),
            #     'wagegrowth': self.economicsData.get("wagegrowth", numpy.nan),
            #     'wagegrowth_chg': self.economicsData.get("wagegrowth_chg", numpy.nan),
            #     'usdeur': self.economicsData.get("usdeur", numpy.nan),
            #     'usdeur_chg': self.economicsData.get("usdeur_chg", numpy.nan),
            #     'usdeur_ch1': self.economicsData.get("usdeur_ch1", numpy.nan),
            #     'usdpeso': self.economicsData.get("usdpeso", numpy.nan),
            #     'usdpeso_chg': self.economicsData.get("usdpeso_chg", numpy.nan),
            #     'usdpeso_ch1': self.economicsData.get("usdpeso_ch1", numpy.nan),
            #     'usdcan': self.economicsData.get("usdcan", numpy.nan),
            #     'usdcan_chg': self.economicsData.get("usdcan_chg", numpy.nan),
            #     'usdcan_ch1': self.economicsData.get("usdcan_ch1", numpy.nan),
            #     'ppi_chg': self.economicsData.get("ppi_chg", numpy.nan),
            #     'ppi_ch1': self.economicsData.get("ppi_ch1", numpy.nan),
            #     'location_cnt': self.equifaxData.get("location_cnt", numpy.nan),
            #     'location_active_cnt': self.equifaxData.get("location_active_cnt", numpy.nan),
            #     'location_inactive_cnt': self.equifaxData.get("location_inactive_cnt", numpy.nan),
            #     'location_inactiveold_cnt': self.equifaxData.get("location_inactiveold_cnt", numpy.nan),
            #     'location_inactivedt_cnt': self.equifaxData.get("location_inactivedt_cnt", numpy.nan),
            #     'location_latitude_avg': self.equifaxData.get("location_latitude_avg", numpy.nan),
            #     'location_longitude_avg': self.equifaxData.get("location_longitude_avg", numpy.nan),
            #     'location_soho_cnt': self.equifaxData.get("location_soho_cnt", numpy.nan),
            #     'location_biz_cnt': self.equifaxData.get("location_biz_cnt", numpy.nan),
            #     'location_res_cnt': self.equifaxData.get("location_res_cnt", numpy.nan),
            #     'location_small_cnt': self.equifaxData.get("location_small_cnt", numpy.nan),
            #     'location_large_cnt': self.equifaxData.get("location_large_cnt", numpy.nan),
            #     'location_unknown_size_cnt': self.equifaxData.get("location_unknown_size_cnt", numpy.nan),
            #     'location_gov_cnt': self.equifaxData.get("location_gov_cnt", numpy.nan),
            #     'location_fedgov_cnt': self.equifaxData.get("location_fedgov_cnt", numpy.nan),
            #     'location_nonprofitind_cnt': self.equifaxData.get("location_nonprofitind_cnt", numpy.nan),
            #     'location_edu_cnt': self.equifaxData.get("location_edu_cnt", numpy.nan),
            #     'location_indsole_cnt': self.equifaxData.get("location_indsole_cnt", numpy.nan),
            #     'location_partner_cnt': self.equifaxData.get("location_partner_cnt", numpy.nan),
            #     'location_limpartner_cnt': self.equifaxData.get("location_limpartner_cnt", numpy.nan),
            #     'location_corp_cnt': self.equifaxData.get("location_corp_cnt", numpy.nan),
            #     'location_scorp_cnt': self.equifaxData.get("location_scorp_cnt", numpy.nan),
            #     'location_llc_cnt': self.equifaxData.get("location_llc_cnt", numpy.nan),
            #     'location_llp_cnt': self.equifaxData.get("location_llp_cnt", numpy.nan),
            #     'location_other_cnt': self.equifaxData.get("location_other_cnt", numpy.nan),
            #     'location_ccorp_cnt': self.equifaxData.get("location_ccorp_cnt", numpy.nan),
            #     'location_nonprofitstat_cnt': self.equifaxData.get("location_nonprofitstat_cnt", numpy.nan),
            #     'location_mutual_cnt': self.equifaxData.get("location_mutual_cnt", numpy.nan),
            #     'location_trust_cnt': self.equifaxData.get("location_trust_cnt", numpy.nan),
            #     'location_lllp_cnt': self.equifaxData.get("location_lllp_cnt", numpy.nan),
            #     'bankrupt_cnt_failrt': self.equifaxData.get("bankrupt_cnt_failrt", numpy.nan),
            #     'bankrupt_cnt_credcls': self.equifaxData.get("bankrupt_cnt_credcls", numpy.nan),
            #     'bankrupt_cnt_field': self.equifaxData.get("bankrupt_cnt_field", numpy.nan),
            #     'corpemployees': self.integrtionsDataObj.get_corpemployees(),#self.equifaxData.get("corpemployees", numpy.nan),
            #     'corpamount': self.integrtionsDataObj.get_revenue_average(), # self.equifaxData.get("corpamount", self.integrtionsDataObj.get_is_revenue_yearly()), ## if not found in equifax, map to revenue,
            #     'creditscore_avg': self.equifaxData.get("creditscore_avg", numpy.nan),
            #     'creditscore_max': self.equifaxData.get("creditscore_max", numpy.nan),
            #     'creditscore_min': self.equifaxData.get("creditscore_min", numpy.nan),
            #     'creditperc_avg': self.equifaxData.get("creditperc_avg", numpy.nan),
            #     'creditperc_max': self.equifaxData.get("creditperc_max", numpy.nan),
            #     'creditperc_min': self.equifaxData.get("creditperc_min", numpy.nan),
            #     'mkt_telscore_avg': self.equifaxData.get("mkt_telscore_avg", numpy.nan),
            #     'mkt_telscore_max': self.equifaxData.get("mkt_telscore_max", numpy.nan),
            #     'mkt_telscore_min': self.equifaxData.get("mkt_telscore_min", numpy.nan),
            #     'mkt_totalscore_avg': self.equifaxData.get("mkt_totalscore_avg", numpy.nan),
            #     'mkt_totalscore_max': self.equifaxData.get("mkt_totalscore_max", numpy.nan),
            #     'mkt_totalscore_min': self.equifaxData.get("mkt_totalscore_min", numpy.nan),
            #     'months_since_update': self.equifaxData.get("months_since_update", numpy.nan),
            #     'legname_occ': self.equifaxData.get("legname_occ", numpy.nan),
            #     'afflname_occ': self.equifaxData.get("afflname_occ", numpy.nan),
            #     'ratio_accounts_payable_cash': self.integrtionsDataObj.get_ratio_accounts_payable_cash(),
            #     'ratio_total_liabilities_cash': self.integrtionsDataObj.get_ratio_total_liabilities_cash(),
            #     'ratio_total_liabilities_assets': self.integrtionsDataObj.get_ratio_total_liabilities_assets(),
            #     'ratio_return_on_equity': self.integrtionsDataObj.get_ratio_returnonequityroe(),
            #     'ratio_return_on_assets': self.integrtionsDataObj.get_ratio_returnonassetsroa(),
            #     'ratio_net_income_ratio': self.integrtionsDataObj.get_is_net_income_ratio(),
            #     'ratio_income_quality_ratio': self.integrtionsDataObj.get_ratio_incomequalityratio(),
            #     'ratio_gross_margin': self.integrtionsDataObj.get_ratio_grossmargin(),
            #     'ratio_equity_multiplier': self.integrtionsDataObj.get_ratio_equitymultiplier(),
            #     'ratio_debt_to_equity': self.integrtionsDataObj.get_ratio_debttoequityratio(),
            #     'ratio_operating_margin': self.integrtionsDataObj.get_ratio_operatingmargin(),
            #     'ratio_cash_ratio': self.integrtionsDataObj.get_ratio_cash_ratio(),
            #     'ratio_accounts_recievable_cash': self.integrtionsDataObj.get_ratio_accounts_recievable_cash(),
            #     'flag_total_liabilities_over_assets': self.integrtionsDataObj.get_custom_total_liabilities_over_assets_ratio(),
            #     'flag_equity_negative': 0 if self.integrtionsDataObj.get_bs_total_equity() >= 0 else 1,
            #     'flag_net_income_negative': 0 if self.integrtionsDataObj.get_is_net_income() >= 0 else 1,
            #     'is_revenue': self.integrtionsDataObj.get_is_revenue(),
            #     'is_operating_expense': self.integrtionsDataObj.get_is_operating_expense(),
            #     'is_net_income': self.integrtionsDataObj.get_is_net_income(),
            #     'is_gross_profit': self.integrtionsDataObj.get_is_gross_profit(),
            #     'is_cost_of_goods_sold': self.integrtionsDataObj.get_is_cost_of_goods_sold(),
            #     'cf_operating_cash_flow': self.integrtionsDataObj.get_cf_operating_cash_flow(),
            #     'cf_cash_at_end_of_period': self.integrtionsDataObj.get_cf_cash_end_of_period(),
            #     'cf_capex': self.integrtionsDataObj.get_cf_capex(),
            #     'bs_total_liabilities_and_equity': self.integrtionsDataObj.get_bs_total_liabilities() + self.integrtionsDataObj.get_bs_total_equity(),
            #     'bs_total_liabilities': self.integrtionsDataObj.get_bs_total_liabilities(),
            #     'bs_total_equity': self.integrtionsDataObj.get_bs_total_equity(),
            #     'bs_total_debt': self.integrtionsDataObj.get_bs_total_liabilities(),
            #     'bs_total_assets': self.integrtionsDataObj.get_bs_total_assets(),
            #     'bs_accounts_receivable': self.integrtionsDataObj.bs_accounts_receivable,
            #     'bs_accounts_payable': self.integrtionsDataObj.bs_accounts_payable,
            #     'review_score': self.integrtionsDataObj.get_review_score(),
            #     'review_cnt': self.integrtionsDataObj.get_review_count(),
            #     'min_age': self.integrtionsDataObj.get_min_age(),
            #     'max_age': self.integrtionsDataObj.get_min_age(),
            #     'lien_count': self.integrtionsDataObj.get_lien_count(),
            #     'lien_most_recent_age': self.integrtionsDataObj.get_lien_most_recent_age(),
            #     'bankruptcy_count': self.integrtionsDataObj.get_bankruptcy_count(),
            #     'bankruptcy_most_recent_age': self.integrtionsDataObj.get_bankruptcy_most_recent_age(),
            #     'judgement_count': self.integrtionsDataObj.get_judgement_count(),
            #     'judgement_most_recent_age': self.integrtionsDataObj.get_judgement_most_recent_age(),
            #     'missing_fields_share': numpy.nan, #TODO
            #     'primnaics_sector': self.equifaxData.get("primnaics_sector", numpy.nan),
            #     'primnaics_subsector': self.equifaxData.get("primnaics_subsector", numpy.nan),
            #     'primnaics_industry': self.equifaxData.get("primnaics_industry", numpy.nan),
            #     'legultstateall': self.integrtionsDataObj.get_legultstateall(),
            #     'primnaicscode': self.integrtionsDataObj.get_primnaicscode(), #self.equifaxData.get("primnaicscode", numpy.nan),                
            #     'corpamount_prec': self.equifaxData.get("corpamount_prec", numpy.nan),
            #     'corpamount_type': self.equifaxData.get("corpamount_type", numpy.nan),
            #     'primnaics_industry_group': self.equifaxData.get("primnaics_industry_group", numpy.nan),
            #     'failrate_avg': self.equifaxData.get("failrate_avg", numpy.nan),
            #     'primsic': self.equifaxData.get("primsic", numpy.nan)
            # }

            data = {
                    "state": self.scoreInput.get("state"),
                    "bus_struct": self.scoreInput.get("bus_struct"),
                    "age_bankruptcy":   self._safe_float(self.scoreInput.get("age_bankruptcy")),
                    "age_judgment": self._safe_float(self.scoreInput.get("age_judgment")),
                    "age_lien": self._safe_float(self.scoreInput.get("age_lien")),
                    "age_business": self._safe_float(self.scoreInput.get("age_business")),
                    "count_bankruptcy": self._safe_float(self.scoreInput.get("count_bankruptcy")),
                    "count_judgment": self._safe_float(self.scoreInput.get("count_judgment")),
                    "count_lien":  self._safe_float(self.scoreInput.get("count_lien")),
                    "count_employees":  self._safe_float(self.scoreInput.get("count_employees")),
                    "city": self.scoreInput.get("city"),
                    "indicator_government": self._safe_float(self.scoreInput.get("indicator_government")),
                    "indicator_federal_government": self._safe_float(self.scoreInput.get("indicator_federal_government")),
                    "indicator_education": self._safe_float(self.scoreInput.get("indicator_education")),
                    "indicator_public": self._safe_float(self.scoreInput.get("indicator_public")),
                    "naics6":  self._safe_float(self.scoreInput.get("naics_code")),
                    "primsic": self._safe_float(self.scoreInput.get("primsic")),
                    "revenue": self._get_financial_value("revenue"),
                    "is_cost_of_goods_sold": self._get_financial_value("is_cost_of_goods_sold"),
                    "is_operating_expense": self._get_financial_value("is_operating_expense"),
                    "is_net_income": self._get_financial_value("is_net_income"),
                    "is_gross_profit": self._get_financial_value("is_gross_profit"),
                    "bs_accounts_receivable": self._get_financial_value("bs_accounts_receivable"),
                    "bs_accounts_payable": self._get_financial_value("bs_accounts_payable"),
                    "bs_total_assets": self._get_financial_value("bs_total_assets"),
                    "bs_total_debt": self._get_financial_value("bs_total_debt"),
                    "bs_total_equity": self._get_financial_value("bs_total_equity"),
                    "bs_total_liabilities_and_equity": self._get_financial_value("bs_total_liabilities_and_equity"),
                    "bs_total_liabilities": self._get_financial_value("bs_total_liabilities"),
                    "cf_capex": self._get_financial_value("cf_capex"),
                    "cf_cash_at_end_of_period": self._get_financial_value("cf_cash_at_end_of_period"),
                    "cf_operating_cash_flow": self._get_financial_value("cf_operating_cash_flow"),
                    "flag_equity_negative": self._safe_float(self.scoreInput.get("flag_equity_negative")),
                    "flag_total_liabilities_over_assets":  self._safe_float(self.scoreInput.get("flag_total_liabilities_over_assets")),
                    "flag_net_income_negative": self._safe_float(self.scoreInput.get("flag_net_income_negative")),
                    "ratio_accounts_payable_cash": self._safe_float(self.scoreInput.get("ratio_accounts_payable_cash")),
                    "ratio_total_liabilities_cash": self._safe_float(self.scoreInput.get("ratio_total_liabilities_cash")),
                    "ratio_total_liabilities_assets": self._safe_float(self.scoreInput.get("ratio_total_liabilities_assets")),
                    "ratio_return_on_equity": self._safe_float(self.scoreInput.get("ratio_return_on_equity")),
                    "ratio_return_on_assets": self._safe_float(self.scoreInput.get("ratio_return_on_assets")),
                    "ratio_net_income_ratio": self._safe_float(self.scoreInput.get("ratio_net_income_ratio")),
                    "ratio_income_quality_ratio": self._safe_float(self.scoreInput.get("ratio_income_quality_ratio")),
                    "ratio_gross_margin": self._safe_float(self.scoreInput.get("ratio_gross_margin")),
                    "ratio_equity_multiplier": self._safe_float(self.scoreInput.get("ratio_equity_multiplier")),
                    "ratio_debt_to_equity": self._safe_float(self.scoreInput.get("ratio_debt_to_equity")),
                    "ratio_operating_margin": self._safe_float(self.scoreInput.get("ratio_operating_margin")),
                    "ratio_cash_ratio": self._safe_float(self.scoreInput.get("ratio_cash_ratio")),
                    "ratio_accounts_recievable_cash": self._safe_float(self.scoreInput.get("ratio_accounts_receivable_cash")),
                    "gdp_pch": self._safe_float(self.economicsData.get("gdp_pch")),
                    "gdp_pc1": self._safe_float(self.economicsData.get("gdp_pc1")),
                    "t10y2y": self._safe_float(self.economicsData.get("t10y2y")),
                    "t10y2y_chg": self._safe_float(self.economicsData.get("t10y2y_chg")),
                    "t10y2y_ch1": self._safe_float(self.economicsData.get("t10y2y_ch1")),
                    "t10y": self._safe_float(self.economicsData.get("t10y")),
                    "t10y_chg": self._safe_float(self.economicsData.get("t10y_chg")),
                    "t10y_ch1": self._safe_float(self.economicsData.get("t10y_ch1")),
                    "t2y": self._safe_float(self.economicsData.get("t2y")),
                    "t2y_chg": self._safe_float(self.economicsData.get("t2y_chg")),
                    "t2y_ch1": self._safe_float(self.economicsData.get("t2y_ch1")),
                    "brent_pch": self._safe_float(self.economicsData.get("brent_pch")),
                    "brent_pc1": self._safe_float(self.economicsData.get("brent_pc1")),
                    "wtispot_pch": self._safe_float(self.economicsData.get("wtispot_pch")),
                    "wtispot_pc1": self._safe_float(self.economicsData.get("wtispot_pc1")),
                    "vix": self._safe_float(self.economicsData.get("vix")),
                    "vix_chg": self._safe_float(self.economicsData.get("vix_chg")),
                    "vix_ch1": self._safe_float(self.economicsData.get("vix_ch1")),
                    "csentiment": self._safe_float(self.economicsData.get("csentiment")),
                    "csentiment_chg": self._safe_float(self.economicsData.get("csentiment_chg")),
                    "csentiment_ch1": self._safe_float(self.economicsData.get("csentiment_ch1")),
                    "dolindx": self._safe_float(self.economicsData.get("dolindx")),
                    "dolindx_chg": self._safe_float(self.economicsData.get("dolindx_chg")),
                    "dolindx_ch1": self._safe_float(self.economicsData.get("dolindx_ch1")),
                    "unemp": self._safe_float(self.economicsData.get("unemp")),
                    "unemp_chg": self._safe_float(self.economicsData.get("unemp_chg")),
                    "unemp_ch1": self._safe_float(self.economicsData.get("unemp_ch1")),
                    "cpi": self._safe_float(self.economicsData.get("cpi")),
                    "cpi_chg": self._safe_float(self.economicsData.get("cpi_chg")),
                    "cpi_ch1": self._safe_float(self.economicsData.get("cpi_ch1")),
                    "cpicore": self._safe_float(self.economicsData.get("cpicore")),
                    "cpicore_chg": self._safe_float(self.economicsData.get("cpicore_chg")),
                    "cpicore_ch1": self._safe_float(self.economicsData.get("cpicore_ch1")),
                    "ccdelinq": self._safe_float(self.economicsData.get("ccdelinq")),
                    "ccdelinq_chg": self._safe_float(self.economicsData.get("ccdelinq_chg")),
                    "ccdelinq_ch1": self._safe_float(self.economicsData.get("ccdelinq_ch1")),
                    "cloandelinq": self._safe_float(self.economicsData.get("cloandelinq")),
                    "cloandelinq_chg": self._safe_float(self.economicsData.get("cloandelinq_chg")),
                    "cloandelinq_ch1": self._safe_float(self.economicsData.get("cloandelinq_ch1")),
                    "busloandelinq": self._safe_float(self.economicsData.get("busloandelinq")),
                    "busloandelinq_chg": self._safe_float(self.economicsData.get("busloandelinq_chg")),
                    "busloandelinq_ch1": self._safe_float(self.economicsData.get("busloandelinq_ch1")),
                    "wagegrowth": self._safe_float(self.economicsData.get("wagegrowth")),
                    "wagegrowth_chg": self._safe_float(self.economicsData.get("wagegrowth_chg")),
                    "usdeur": self._safe_float(self.economicsData.get("usdeur")),
                    "usdeur_chg": self._safe_float(self.economicsData.get("usdeur_chg")),
                    "usdeur_ch1": self._safe_float(self.economicsData.get("usdeur_ch1")),
                    "usdpeso": self._safe_float(self.economicsData.get("usdpeso")),
                    "usdpeso_chg": self._safe_float(self.economicsData.get("usdpeso_chg")),
                    "usdpeso_ch1": self._safe_float(self.economicsData.get("usdpeso_ch1")),
                    "usdcan": self._safe_float(self.economicsData.get("usdcan")),
                    "usdcan_chg": self._safe_float(self.economicsData.get("usdcan_chg")),
                    "usdcan_ch1": self._safe_float(self.economicsData.get("usdcan_ch1")),
                    "ppi_chg": self._safe_float(self.economicsData.get("ppi_chg")),
                    "ppi_ch1": self._safe_float(self.economicsData.get("ppi_ch1")),
                    "count_reviews": self._safe_float(self.scoreInput.get("count_reviews")),
                    "score_reviews": self._safe_float(self.scoreInput.get("score_reviews")),
                }
    
    
            return data
        except Exception:
            raise