export const ACTIVE_DECISIONING_TYPE_CUSTOM_WORKFLOW = "custom_workflow";

export const CASE_STATUS = {
	INVITED: 1,
	INVITE_EXPIRED: 2,
	ONBOARDING: 3,
	UNDER_MANUAL_REVIEW: 4,
	MANUALLY_APPROVED: 5,
	AUTO_APPROVED: 6,
	SCORE_CALCULATED: 7,
	MANUALLY_REJECTED: 8,
	ARCHIVED: 9,
	PENDING_DECISION: 10,
	INFORMATION_REQUESTED: 11,
	SUBMITTED: 12,
	AUTO_REJECTED: 13,
	RISK_ALERT: 14,
	INVESTIGATING: 15,
	DISMISSED: 16,
	ESCALATED: 17,
	PAUSED: 18,
	INFORMATION_UPDATED: 19
} as const;
