const {
	VITE_API_ENDPOINT,
	VITE_ELECTRONIC_CONSENT,
	VITE_LD_CLIENT_KEY,
	VITE_PORT,
	VITE_SERVICE_AUTH,
	VITE_SERVICE_CASE,
	VITE_SERVICE_INTEGRATION,
	VITE_SERVICE_NOTIFICATION,
	VITE_SERVICE_REPORT,
	VITE_SERVICE_SCORE,
} = import.meta.env;

export const envConfig = {
	VITE_API_ENDPOINT,
	VITE_ELECTRONIC_CONSENT,
	VITE_LD_CLIENT_KEY,
	VITE_PORT,
	VITE_SERVICE_AUTH,
	VITE_SERVICE_CASE,
	VITE_SERVICE_INTEGRATION,
	VITE_SERVICE_NOTIFICATION,
	VITE_SERVICE_REPORT,
	VITE_SERVICE_SCORE,
} as const;
