const FEATURE_FLAGS = {
	DOS_277_MICROSITES_SETUP: "DOS_277_MICROSITES_SETUP",
	BEST_23_CUSTOMER_CASES_DETAILS: "BEST_23_CUSTOMER_CASES_DETAILS",
	PAT_779_CREATE_AND_UPDATE_CUSTOM_SUBROLES:
		"PAT_779_CREATE_AND_UPDATE_CUSTOM_SUBROLES",
};
export default FEATURE_FLAGS;
