export const CASE_STATUS = {
	INVITED: 1, // deprecated: to be removed
	INVITE_EXPIRED: 2, // deprecated: to be removed
	ONBOARDING: 3,
	UNDER_MANUAL_REVIEW: 4,
	MANUALLY_APPROVED: 5,
	AUTO_APPROVED: 6,
	SCORE_CALCULATED: 7,
	MANUALLY_REJECTED: 8,
	ARCHIVED: 9,
	PENDING_DECISION: 10,
	INFORMATION_REQUESTED: 11,
	SUBMITTED: 12,
	AUTO_REJECTED: 13,
	RISK_ALERT: 14,
	INVESTIGATING: 15,
	DISMISSED: 16,
	ESCALATED: 17,
	PAUSED: 18,
	INFORMATION_UPDATED: 19,
	CREATED: 20,
} as const;

export enum CASE_STATUS_ENUM {
	INVITED = "INVITED",
	INVITE_EXPIRED = "INVITE_EXPIRED", // deprecated: to be removed
	ONBOARDING = "ONBOARDING",
	UNDER_MANUAL_REVIEW = "UNDER_MANUAL_REVIEW",
	MANUALLY_APPROVED = "MANUALLY_APPROVED",
	AUTO_APPROVED = "AUTO_APPROVED",
	SCORE_CALCULATED = "SCORE_CALCULATED",
	MANUALLY_REJECTED = "MANUALLY_REJECTED",
	ARCHIVED = "ARCHIVED",
	PENDING_DECISION = "PENDING_DECISION",
	INFORMATION_REQUESTED = "INFORMATION_REQUESTED",
	SUBMITTED = "SUBMITTED",
	AUTO_REJECTED = "AUTO_REJECTED",
	RISK_ALERT = "RISK_ALERT",
	INVESTIGATING = "INVESTIGATING",
	DISMISSED = "DISMISSED",
	ESCALATED = "ESCALATED",
	PAUSED = "PAUSED",
	INFORMATION_UPDATED = "INFORMATION_UPDATED",
	CREATED = "CREATED",
}

export const UPDATABLE_ONBOARDING_STATUSES = [
	CASE_STATUS_ENUM.AUTO_APPROVED,
	CASE_STATUS_ENUM.AUTO_REJECTED,
	CASE_STATUS_ENUM.UNDER_MANUAL_REVIEW,
	CASE_STATUS_ENUM.ARCHIVED,
	CASE_STATUS_ENUM.SUBMITTED,
	CASE_STATUS_ENUM.MANUALLY_APPROVED,
	CASE_STATUS_ENUM.MANUALLY_REJECTED,
	CASE_STATUS_ENUM.SCORE_CALCULATED,
	CASE_STATUS_ENUM.PENDING_DECISION,
	CASE_STATUS_ENUM.INFORMATION_REQUESTED,
	CASE_STATUS_ENUM.INFORMATION_UPDATED,
	CASE_STATUS_ENUM.INVITED,
	CASE_STATUS_ENUM.CREATED,
];

export const UPDATABLE_RISK_STATUSES = [
	CASE_STATUS_ENUM.RISK_ALERT,
	CASE_STATUS_ENUM.INVESTIGATING,
	CASE_STATUS_ENUM.ESCALATED,
	CASE_STATUS_ENUM.PAUSED,
];

export const ONBOARDING_STATUS_TRANSITIONS = [
	CASE_STATUS_ENUM.UNDER_MANUAL_REVIEW,
	CASE_STATUS_ENUM.INFORMATION_REQUESTED,
	CASE_STATUS_ENUM.MANUALLY_APPROVED,
	CASE_STATUS_ENUM.MANUALLY_REJECTED,
];

export const RISK_STATUS_TRANSITIONS = [
	CASE_STATUS_ENUM.RISK_ALERT,
	CASE_STATUS_ENUM.INVESTIGATING,
	CASE_STATUS_ENUM.ESCALATED,
	CASE_STATUS_ENUM.PAUSED,
	CASE_STATUS_ENUM.DISMISSED,
];
