export const FEATURE_FLAGS = {
	DOS_48_WORTH_360_REPORT: "DOS_48_WORTH_360_REPORT",
	DOS_277_MICROSITES_SETUP: "DOS_277_MICROSITES_SETUP",
	BEST_23_CUSTOMER_CASES_DETAILS: "BEST_23_CUSTOMER_CASES_DETAILS",
	DOS_445_VERDATA_DOCTORS_RESULT: "DOS_445_VERDATA_DOCTORS_RESULT",
	DOS_558_HANDLE_GIACT_CA30_TOOLTIP: "DOS_558_HANDLE_GIACT_CA30_TOOLTIP",
	BEST_65_PROXY_FACT: "BEST_65_PROXY_FACT",
	DOS_948_TRACK_APPLICATION_COMPLETION:
		"DOS_948_TRACK_APPLICATION_COMPLETION",
	PAT_874_CM_APP_EDITING: "PAT_874_CM_APP_EDITING",
	PAT_926_PAUSE_DECISIONING: "PAT_926_PAUSE_DECISIONING",
	PAT_961_DISPLAY_INTEGRATIONS_RUNNING:
		"PAT_961_DISPLAY_INTEGRATIONS_RUNNING",
	PAT_984_CUSTOMIZE_AGING_THRESHOLDS_WEBHOOK_MESSAGES:
		"PAT_984_CUSTOMIZE_AGING_THRESHOLDS_WEBHOOK_MESSAGES",
	FOTC_79_APPROVAL_WORKFLOWS: "FOTC_79_APPROVAL_WORKFLOWS",
	PAT_896_WORTH_SCORE_ONBOARDING_RESULTS:
		"PAT_896_WORTH_SCORE_ONBOARDING_RESULTS",
	/** SSN encryption + KYC reveal (eye) / last-4 display */
	BEST_87_SSN_ENCRYPTION: "BEST_87_SSN_ENCRYPTION",
};
export default FEATURE_FLAGS;
