import { hostname } from "os";
import dotenv from "dotenv";
import { isValidString } from "#utils/validation";

dotenv.config({
	path: process.env.NODE_ENV === "production" ? ".env" : ".env.local"
});

const parseBool = (str: string | undefined, valueIfEmpty = false) => {
	if (str && isValidString(str)) {
		return str.toLowerCase() === "true";
	}
	return valueIfEmpty;
};

const {
	NODE_ENV,
	DOPPLER_ENVIRONMENT,
	CONFIG_APP_PORT,
	CONFIG_HEALTH_CHECK_MODE,
	SUBDOMAIN,
	CONFIG_WORTH_ADMIN_USER_POOL_ID,
	CONFIG_CUSTOMER_USER_POOL_ID,
	CONFIG_APPLICANT_USER_POOL_ID,
	CONFIG_APPLICANT_CLIENT_ID,
	CONFIG_WORTH_ADMIN_CLIENT_ID,
	CONFIG_CUSTOMER_CLIENT_ID,
	CONFIG_LD_SDK_KEY,
	CONFIG_LD_INTIALIZATION_TIMEOUT,
	CONFIG_LD_TEST_FLAGS_FILE,
	CONFIG_DB_HOST,
	CONFIG_DB_PORT,
	CONFIG_DB_USER,
	CONFIG_DB_PASSWORD,
	CONFIG_DB_NAME,
	CONFIG_DB_MAX_CONNECTIONS,
	CONFIG_CASE_BASE_URL,
	CONFIG_CASE_SERVICE_URL,
	CONFIG_CASE_API_PREFIX,
	CONFIG_CASE_HEALTH_PATH,
	CONFIG_WAREHOUSE_SERVICE_URL,
	CONFIG_WAREHOUSE_HEALTH_PATH,
	CONFIG_AUTH_BASE_URL,
	CONFIG_REDIS_URL,
	CONFIG_REDIS_HOST,
	CONFIG_REDIS_PORT,
	CONFIG_REDIS_USERNAME,
	CONFIG_REDIS_PASSWORD,
	CONFIG_REDIS_EC_CLUSTER,
	CONFIG_REDIS_DISABLE_TLS,
	CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED,
	CONFIG_REDIS_RECONNECT_MAX_WAIT,
	CONFIG_REDIS_KEY_PREFIX,
	CONFIG_KAFKA_BROKERS,
	CONFIG_KAFKA_CLIENT_ID,
	CONFIG_KAFKA_GROUP_ID,
	CONFIG_KAFKA_SSL_ENABLED,
	CONFIG_KAFKA_SASL_USERNAME,
	CONFIG_KAFKA_SASL_PASSWORD,
	CONFIG_CASES_KAFKA_TOPIC,
	CONFIG_WORKFLOWS_KAFKA_TOPIC,
	CONFIG_NOTIFICATIONS_KAFKA_TOPIC,
	CONFIG_BUSINESS_KAFKA_TOPIC,
	CONFIG_EXPORT_MAX_RECORDS,
	CONFIG_FRONTEND_LOCAL_BASE_URLS
} = process.env;

export const envConfig = {
	ENV: NODE_ENV,
	DOPPLER_ENV: DOPPLER_ENVIRONMENT,
	HOSTNAME: hostname(),
	APP_PORT: parseFloat(CONFIG_APP_PORT ?? "3007"),
	HEALTH_CHECK_MODE: parseBool(CONFIG_HEALTH_CHECK_MODE, false),
	SUBDOMAIN,

	// Cognito Configuration
	WORTH_ADMIN_USER_POOL_ID: CONFIG_WORTH_ADMIN_USER_POOL_ID,
	CUSTOMER_USER_POOL_ID: CONFIG_CUSTOMER_USER_POOL_ID,
	APPLICANT_USER_POOL_ID: CONFIG_APPLICANT_USER_POOL_ID,
	APPLICANT_CLIENT_ID: CONFIG_APPLICANT_CLIENT_ID,
	WORTH_ADMIN_CLIENT_ID: CONFIG_WORTH_ADMIN_CLIENT_ID,
	CUSTOMER_CLIENT_ID: CONFIG_CUSTOMER_CLIENT_ID,

	// LaunchDarkly Configuration
	LD_SDK_KEY: CONFIG_LD_SDK_KEY,
	LD_INTIALIZATION_TIMEOUT: parseInt(CONFIG_LD_INTIALIZATION_TIMEOUT ?? ""),
	LD_TEST_FLAGS_FILE: CONFIG_LD_TEST_FLAGS_FILE,

	// Database Configuration
	DB_HOST: CONFIG_DB_HOST,
	DB_PORT: parseInt(CONFIG_DB_PORT ?? "5432"),
	DB_USER: CONFIG_DB_USER,
	DB_PASSWORD: CONFIG_DB_PASSWORD,
	DB_NAME: CONFIG_DB_NAME,
	DB_MAX_CONNECTIONS: parseInt(CONFIG_DB_MAX_CONNECTIONS ?? "20"),

	// External Services Configuration
	CASE_BASE_URL: CONFIG_CASE_BASE_URL,
	CASE_SERVICE_URL: CONFIG_CASE_SERVICE_URL,
	CASE_API_PREFIX: CONFIG_CASE_API_PREFIX,
	CASE_HEALTH_PATH: CONFIG_CASE_HEALTH_PATH,
	WAREHOUSE_SERVICE_URL: CONFIG_WAREHOUSE_SERVICE_URL,
	WAREHOUSE_HEALTH_PATH: CONFIG_WAREHOUSE_HEALTH_PATH,
	AUTH_BASE_URL: CONFIG_AUTH_BASE_URL,

	// Redis Configuration
	REDIS_URL: CONFIG_REDIS_URL,
	REDIS_HOST: CONFIG_REDIS_HOST,
	REDIS_PORT: CONFIG_REDIS_PORT,
	REDIS_USERNAME: CONFIG_REDIS_USERNAME,
	REDIS_PASSWORD: CONFIG_REDIS_PASSWORD,
	REDIS_EC_CLUSTER: parseBool(CONFIG_REDIS_EC_CLUSTER, true),
	REDIS_DISABLE_TLS: parseBool(CONFIG_REDIS_DISABLE_TLS, true),
	REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED: parseBool(CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED, true),
	REDIS_RECONNECT_MAX_WAIT: parseInt(CONFIG_REDIS_RECONNECT_MAX_WAIT ?? "2000"),
	REDIS_KEY_PREFIX: CONFIG_REDIS_KEY_PREFIX || "",

	// Kafka Configuration
	KAFKA_BROKERS: CONFIG_KAFKA_BROKERS,
	KAFKA_CLIENT_ID: CONFIG_KAFKA_CLIENT_ID,
	KAFKA_GROUP_ID: CONFIG_KAFKA_GROUP_ID,
	KAFKA_SSL_ENABLED: parseBool(CONFIG_KAFKA_SSL_ENABLED, false),
	KAFKA_SASL_USERNAME: CONFIG_KAFKA_SASL_USERNAME,
	KAFKA_SASL_PASSWORD: CONFIG_KAFKA_SASL_PASSWORD,
	CASES_KAFKA_TOPIC: CONFIG_CASES_KAFKA_TOPIC,
	WORKFLOWS_KAFKA_TOPIC: CONFIG_WORKFLOWS_KAFKA_TOPIC,
	NOTIFICATIONS_KAFKA_TOPIC: CONFIG_NOTIFICATIONS_KAFKA_TOPIC,
	BUSINESS_KAFKA_TOPIC: CONFIG_BUSINESS_KAFKA_TOPIC,

	// Export CSV Configuration
	EXPORT_MAX_RECORDS: parseInt(CONFIG_EXPORT_MAX_RECORDS ?? "5000"),

	// Frontend CORS Configuration
	FRONTEND_LOCAL_BASE_URLS: CONFIG_FRONTEND_LOCAL_BASE_URLS
};
