const FEATURE_FLAGS = {
	DOS_277_MICROSITES_SETUP: "DOS_277_MICROSITES_SETUP",
	BEST_23_CUSTOMER_CASES_DETAILS: "BEST_23_CUSTOMER_CASES_DETAILS",
	FOTC_79_APPROVAL_WORKFLOWS: "FOTC_79_APPROVAL_WORKFLOWS",
	PAT_984_CUSTOMIZE_AGING_THRESHOLDS_WEBHOOK_MESSAGES:
		"PAT_984_CUSTOMIZE_AGING_THRESHOLDS_WEBHOOK_MESSAGES",
};
export default FEATURE_FLAGS;
