export const CASE_STATUS = {
	INVITED: 1, // deprecated: to be removed
	INVITE_EXPIRED: 2, // deprecated: to be removed
	ONBOARDING: 3,
	UNDER_MANUAL_REVIEW: 4,
	MANUALLY_APPROVED: 5,
	AUTO_APPROVED: 6,
	SCORE_CALCULATED: 7,
	REJECTED: 8,
	ARCHIVED: 9,
	PENDING_DECISION: 10,
	INFORMATION_REQUESTED: 11,
	SUBMITTED: 12,
	AUTO_REJECTED: 13,
	INFORMATION_UPDATED: 19,
} as const;

export enum CASE_STATUS_ENUM {
	INVITED = "INVITED", // deprecated: to be removed
	INVITE_EXPIRED = "INVITE_EXPIRED", // deprecated: to be removed
	ONBOARDING = "ONBOARDING",
	UNDER_MANUAL_REVIEW = "UNDER_MANUAL_REVIEW",
	MANUALLY_APPROVED = "MANUALLY_APPROVED",
	AUTO_APPROVED = "AUTO_APPROVED",
	SCORE_CALCULATED = "SCORE_CALCULATED",
	REJECTED = "REJECTED",
	ARCHIVED = "ARCHIVED",
	SUBMITTED = "SUBMITTED",
	AUTO_REJECTED = "AUTO_REJECTED",
	PENDING_DECISION = "PENDING_DECISION",
	INFORMATION_REQUESTED = "INFORMATION_REQUESTED",
	MANUALLY_REJECTED = "MANUALLY_REJECTED",
	RISK_ALERT = "RISK_ALERT",
	INVESTIGATING = "INVESTIGATING",
	ESCALATED = "ESCALATED",
	DISMISSED = "DISMISSED",
	PAUSED = "PAUSED",
	INFORMATION_UPDATED = "INFORMATION_UPDATED",
}

export const allReviewModalStatuses = [
	CASE_STATUS_ENUM.ONBOARDING,
	CASE_STATUS_ENUM.UNDER_MANUAL_REVIEW,
	CASE_STATUS_ENUM.INFORMATION_REQUESTED,
	CASE_STATUS_ENUM.MANUALLY_APPROVED,
	CASE_STATUS_ENUM.MANUALLY_REJECTED,
	CASE_STATUS_ENUM.RISK_ALERT,
	CASE_STATUS_ENUM.INVESTIGATING,
	CASE_STATUS_ENUM.DISMISSED,
	CASE_STATUS_ENUM.ESCALATED,
	CASE_STATUS_ENUM.INFORMATION_UPDATED,
];
