const STORAGE_SIZE_IN_MB = 1024 * 1024;
const CREATE_BUSINESSES_TIMEOUT = 90000; // 90 seconds

// Onboarding Setup IDs
const ONBOARDING_SETUP_ID = {
	INTERNATIONAL_BUSINESS: 7,
} as const;

export { STORAGE_SIZE_IN_MB, CREATE_BUSINESSES_TIMEOUT, ONBOARDING_SETUP_ID };
