const FEATURE_FLAGES = {
	WIN_869_SEND_BUSINESS_INVITATION: "WIN-869-SEND-BUSINESS-INVITATION",
	WIN_1426_OCR_EASYFLOW: "WIN_1426_OCR_EASYFLOW",
	DOS_48_WORTH_360_REPORT: "DOS_48_WORTH_360_REPORT",
	PAT_123_GET_BUSINESS_DATA: "PAT_123_GET_BUSINESS_DATA",
	DOS_90_OCR_INTEGRATION: "DOS_90_OCR_INTEGRATION",
	PAT_80_FACTS: "PAT_80_FACTS",
	DOS_277_MICROSITES_SETUP: "DOS_277_MICROSITES_SETUP",
	WIN_740_PURGE_BUSINESS: "WIN-740-PURGE_BUSINESS",
	DOS_501_ADD_HUBSPOT_TRACKING_PIXEL: "DOS_501_ADD_HUBSPOT_TRACKING_PIXEL",
	DOS_558_HANDLE_GIACT_CA30_TOOLTIP: "DOS_558_HANDLE_GIACT_CA30_TOOLTIP",
	PAT_466_TRIGGERING_APPLICATION_EDIT: "PAT_466_TRIGGERING_APPLICATION_EDIT",
	DOS_52_CASE_MANAGEMENT_V2: "DOS_52_CASE_MANAGEMENT_V2",
	FOTC_1_ENABLE_SAML_SSO: "FOTC_1_ENABLE_SAML_SSO",
	PAT_703_USER_MANAGEMENT_V2: "PAT_703_USER_MANAGEMENT_V2",
	PAT_663_HELPER_BOX_CUSTOMER_ADMIN_WEBAPP:
		"PAT_663_HELPER_BOX_CUSTOMER_ADMIN_WEBAPP",
	PAT_805_CUSTOMER_MICROSITE: "PAT_805_CUSTOMER_MICROSITE",
	PAT_779_ENABLE_CUSTOM_ROLES_FEATURE: "PAT_779_ENABLE_CUSTOM_ROLES_FEATURE",
	FOTC_79_APPROVAL_WORKFLOWS: "FOTC_79_APPROVAL_WORKFLOWS",
};

export default FEATURE_FLAGES;
